import groovy.json.JsonOutput
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Random
import java.util.regex.Pattern
import java.util.regex.Matcher


/*
 * initialize the pipeline
 */

MAVEN_VERSION = "Maven 3.x"
PROJECT_FOLDER = "datatrail-plugin/"

pipeline {
  agent any
    options {
        timeout(time: 1, unit: 'HOURS')
    }
         environment {
            JENKINS_HOME = "/var/lib/jenkins"
            SONAR_URL = "https://sonarqube.wada-ama.org"
            JIRA_SITE = 'wada-ama.atlassian.net'
            GIT_PROJECT = "ADAMS"
            GIT_REPOSITORY = "datatrail-plugins"
            BUILD_NUMBER = VersionNumber([
                versionNumberString : '${BUILD_DATE_FORMATTED,"yyDDD"}${BUILDS_TODAY,XX}',
                projectStartDate : '1969-12-31',
                worstResultForIncrement: 'NOT_BUILT'
              ])

            POM_ARTIFACTID = getPomValue(PROJECT_FOLDER, Pom.ARTIFACT_ID)
            POM_VERSION = getPomValue(PROJECT_FOLDER, Pom.VERSION)
            POM_GROUPID = getPomValue(PROJECT_FOLDER, Pom.GROUP_ID)
            DATATRAIL_VERSION = getPomValue(PROJECT_FOLDER, Pom.VERSION)
            BUILD_VERSION = "$DATATRAIL_VERSION-$BUILD_NUMBER"
         }



    stages {
        stage("Env Variables") {
            steps {
                sh "printenv"
            }
        }

         stage('Maven build, test and ship to Nexus') {
            when { 
                not { buildingTag() } 
            }
            steps {
                dir(PROJECT_FOLDER){
                    configFileProvider([configFile(fileId: 'fa4c4c5b-29b3-46f1-8cd8-5b83b07f491c', targetLocation: '.mvn/jvm.config')]) {
                        configFileProvider([configFile(fileId: '59d605db-7b8a-47c3-b220-6af4dc4facf0', variable: 'MAVEN_SETTINGS_XML')]) {
                            withCredentials([usernameColonPassword(credentialsId: 'nexus-server', variable: 'NEXUSCREDS')]) {
                                withCredentials([string(credentialsId: 'sonar-scan', variable: 'TOKEN')]) {
                                    wrap([$class: 'BuildUser']) {
                                        withMaven(
                                            maven: MAVEN_VERSION,
                                        ){
                                            sh  """mvn \
                                                -Dwada.scm.tag=builds/${BUILD_VERSION} \
                                                -Dsonar.login=${TOKEN} \
                                                -Dsonar.host.url=${SONAR_URL} \
                                                -Dsonar.branch.name=${GIT_BRANCH} \
                                                -Dsonar.projectKey=Datanucleus.DataTrail \
                                                -DdeployAtEnd=true \
                                                -Dwada.scm.commitId=${GIT_COMMIT} \
                                                -Dwada.build.timestamp=${BUILD_TIMESTAMP} \
                                                -Dwada.build.user="${BUILD_USER_EMAIL}" \
                                                -Dbuild.jobName="${JOB_NAME}" \
                                                -Dmaven.test.skip=false \
                                                -Dsonar.projectKey=Datanucleus.DataTrail \
                                                -Dwada.build.number=${BUILD_NUMBER} \
                                                -Dwada.scm.branch=${GIT_BRANCH}  \
                                                clean deploy sonar:sonar """
                                        }
                                    }
                                 }
                            }
                        }
                    }
                }
            }
            post {
                failure {
                    buildDescription "Failed to build version ${DATATRAIL_VERSION}-${env.RELEASE_BUILD_NUMBER}"
                }
                success {
                    buildDescription "Built version ${DATATRAIL_VERSION}-${env.RELEASE_BUILD_NUMBER}"
                }                 
            }
         }

          stage('GIT Tag') {
            when { 
                not { changeRequest() } 
                not { buildingTag() } 
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'bitbucket-server', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh "git tag builds/$BUILD_VERSION"
                    sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.wada-ama.org/scm/adams-ng/paperless-api.git builds/$BUILD_VERSION"
                }                
            }
        } 
        
     }
}



def renderTemplate(input, binding) {
    def engine = new groovy.text.GStringTemplateEngine()
    def template = engine.createTemplate(input).make([environments: binding])
    return template.toString()
}

String gitTagMessage(name, key) {
    msg = sh(script: "git tag -n10000 -l ${name}", returnStdout: true)?.trim()
    String[] values = msg.substring(name.size()+1, msg.size()).split(",")
    for (it in values) {
        item = it.split(":")
        if(item[0]==key) {
            value = item[1]
            return value
        }
    }
    return null
}

enum Pom {
    VERSION ("project.version"),
    ARTIFACT_ID ("project.artifactId"),
    GROUP_ID ("project.groupId")

    private String fieldname

    Pom(String fieldname){
        this.fieldname = fieldname
    }

    String getFieldname(){
        fieldname
    }
}

String getPomValue( folder, Pom field){
            withMaven(
                 maven: MAVEN_VERSION,
                 traceability: 'false'
            ){
                dir(folder){
                 version = sh ( script: "mvn help:evaluate -Dexpression=${field.fieldname} -q -DforceStdout", returnStdout: true).trim()
                }
            }
    return version
}